export const SIGN_OUT = "SIGN_OUT";
export const SIGN_IN = "SIGN_IN";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const AUTH_USER = "AUTH_USER";

export const ERROR_GLOBAL = "ERROR_GLOBAL";
export const SUCCESS_GLOBAL = "SUCCESS_GLOBAL";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";

export const GET_YOUTUBE_DATA = "GET_YOUTUBE_DATA";
export const CLEAR_YOUTUBE_DATA = "CLEAR_YOUTUBE_DATA";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const UPDATE_YOUTUBE_DATA = "UPDATE_YOUTUBE_DATA";

export const ADD_REQUEST = "ADD_REQUEST";
export const CLEAR_CURRENT_REQUEST = "CLEAR_CURRENT_REQUEST";
export const SET_CURRENT_REQUEST = "SET_CURRENT_REQUEST";
export const UPDATE_USER_REQUESTS = "UPDATE_USER_REQUESTS";
